name: Build and Release

on:
  push:
    tags:
      - 'v*' # e.g. v1.0.0 etc

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Get repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Build release ver
        run: dotnet publish -c Release -r win-x64 --self-contained true /p:PublishReadyToRun=true /p:PublishSingleFile=true /p:IncludeNativeLibrariesForSelfExtract=true

      - name: Find .exe for release
        id: upload
        shell: pwsh
        run: |
          $exePath = Get-ChildItem -Path WoWSChatTranslator\bin\Release\net8.0-windows\win-x64\publish -Recurse -Filter WoWSChatTranslator.exe | Select-Object -First 1 | % { $_.FullName }
          "FILE_PATH=$exePath" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ env.FILE_PATH }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
